import Footer from '@/components/Footer';
import Header from '@/components/Header';
import { LayoutProps } from '@/helper/Types/game';
import Providers from '@/store/Proveders';
import Head from 'next/head';

export default function Layout({ children, title }: LayoutProps) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Providers>
        <div className="page">
          <Header />
          {children}
          <Footer />
        </div>
      </Providers>
    </>
  );
}
